services:
  backend-api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    # O healthcheck deve ser removido, pois estava causando o erro "unhealthy"

  frontend-web: # <-- Use este nome de serviço consistente
    build: ./frontend # <-- O Caminho CORRETO para a sua pasta
    ports:
      - "8080:80" # Porta acessível
    volumes:
      - ./frontend:/var/www/html # Volume para o caminho correto
    depends_on:
      - backend-api